name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  YARN_CACHE_FOLDER: ~/.yarn
  PKG_CACHE_PATH: ~/.pkg

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ${{ env.YARN_CACHE_FOLDER }}
          key: ${{ runner.os }}-yarn
      - uses: actions/cache@v2
        with:
          path: ${{ env.PKG_CACHE_PATH }}
          key: ${{ runner.os }}-pkg
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ github.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
